
--
-- SHT.GR SCHEMA
-- CREATED BY TASOS PAPALYRAS
--

--
-- POSTS
--

CREATE TABLE `posts` (
	`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`title` VARCHAR(128) NOT NULL UNIQUE,
    `description` VARCHAR(256) NOT NULL,
    `slug` VARCHAR(128) NOT NULL UNIQUE,
	`content` TEXT NOT NULL,
    `date` TIMESTAMP DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
